# Form implementation generated from reading ui file 'absorbsubmodule.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from gitfourchette.qt import *


class Ui_AbsorbSubmodule(object):
    def setupUi(self, AbsorbSubmodule):
        AbsorbSubmodule.setObjectName("AbsorbSubmodule")
        AbsorbSubmodule.resize(321, 204)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.MinimumExpanding, QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(AbsorbSubmodule.sizePolicy().hasHeightForWidth())
        AbsorbSubmodule.setSizePolicy(sizePolicy)
        self.verticalLayout = QVBoxLayout(AbsorbSubmodule)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label1 = QLabel(parent=AbsorbSubmodule)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label1.sizePolicy().hasHeightForWidth())
        self.label1.setSizePolicy(sizePolicy)
        self.label1.setWordWrap(True)
        self.label1.setObjectName("label1")
        self.verticalLayout.addWidget(self.label1)
        self.widget = QWidget(parent=AbsorbSubmodule)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QLabel(parent=self.widget)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.comboBox = QComboBox(parent=self.widget)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.MinimumExpanding, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.setItemText(0, "origin")
        self.horizontalLayout.addWidget(self.comboBox)
        self.verticalLayout.addWidget(self.widget)
        self.label2 = QLabel(parent=AbsorbSubmodule)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label2.sizePolicy().hasHeightForWidth())
        self.label2.setSizePolicy(sizePolicy)
        self.label2.setWordWrap(True)
        self.label2.setObjectName("label2")
        self.verticalLayout.addWidget(self.label2)
        self.buttonBox = QDialogButtonBox(parent=AbsorbSubmodule)
        self.buttonBox.setOrientation(Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QDialogButtonBox.StandardButton.Cancel|QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(AbsorbSubmodule)
        self.buttonBox.accepted.connect(AbsorbSubmodule.accept) # type: ignore
        self.buttonBox.rejected.connect(AbsorbSubmodule.reject) # type: ignore
        QMetaObject.connectSlotsByName(AbsorbSubmodule)

    def retranslateUi(self, AbsorbSubmodule):
        _translate = QCoreApplication.translate
        AbsorbSubmodule.setWindowTitle(_translate("AbsorbSubmodule", "Absorb submodule"))
        self.label1.setText(_translate("AbsorbSubmodule", "Do you want the Git repository {sub} to be absorbed as a submodule of {super}?"))
        self.label.setText(_translate("AbsorbSubmodule", "Submodule remote:"))
        self.label2.setText(_translate("AbsorbSubmodule", "If you choose to proceed, {super} will assume control of the “.git” directory in {sub}. You will not be able to use {sub} as an independent repository. This cannot be undone!"))
