# Form implementation generated from reading ui file 'aboutdialog.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from gitfourchette.qt import *


class Ui_AboutDialog(object):
    def setupUi(self, AboutDialog):
        AboutDialog.setObjectName("AboutDialog")
        AboutDialog.setWindowModality(Qt.WindowModality.ApplicationModal)
        AboutDialog.resize(329, 434)
        self.verticalLayout = QVBoxLayout(AboutDialog)
        self.verticalLayout.setSpacing(2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.iconLabel = QLabel(parent=AboutDialog)
        self.iconLabel.setText("ICON")
        self.iconLabel.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.iconLabel.setObjectName("iconLabel")
        self.verticalLayout.addWidget(self.iconLabel)
        self.softwareName = QLabel(parent=AboutDialog)
        self.softwareName.setText("<span style=\'font-size: 24pt\'>{0} <span style=\'font-size: 20pt\'>{1}")
        self.softwareName.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.softwareName.setObjectName("softwareName")
        self.verticalLayout.addWidget(self.softwareName)
        self.label_4 = QLabel(parent=AboutDialog)
        self.label_4.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.label_5 = QLabel(parent=AboutDialog)
        self.label_5.setText("Copyright © 2023 Iliyas Jorio")
        self.label_5.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.label_3 = QLabel(parent=AboutDialog)
        self.label_3.setText("<a href=\"https://github.com/jorio/gitfourchette\">https://github.com/jorio/gitfourchette</a>")
        self.label_3.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_3.setOpenExternalLinks(True)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.horizontalLayout = QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.donateButton = QPushButton(parent=AboutDialog)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.donateButton.sizePolicy().hasHeightForWidth())
        self.donateButton.setSizePolicy(sizePolicy)
        self.donateButton.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.donateButton.setFlat(True)
        self.donateButton.setObjectName("donateButton")
        self.horizontalLayout.addWidget(self.donateButton)
        spacerItem1 = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem2 = QSpacerItem(20, 16, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Fixed)
        self.verticalLayout.addItem(spacerItem2)
        self.plainTextEdit = QPlainTextEdit(parent=AboutDialog)
        self.plainTextEdit.setTabChangesFocus(True)
        self.plainTextEdit.setReadOnly(True)
        self.plainTextEdit.setPlainText("")
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.verticalLayout.addWidget(self.plainTextEdit)
        self.buttonBox = QDialogButtonBox(parent=AboutDialog)
        self.buttonBox.setStandardButtons(QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(AboutDialog)
        self.buttonBox.accepted.connect(AboutDialog.close) # type: ignore
        QMetaObject.connectSlotsByName(AboutDialog)

    def retranslateUi(self, AboutDialog):
        _translate = QCoreApplication.translate
        AboutDialog.setWindowTitle(_translate("AboutDialog", "About {0}"))
        self.label_4.setText(_translate("AboutDialog", "The comfy Git UI for Linux."))
        self.donateButton.setText(_translate("AboutDialog", "Donate"))
