# Form implementation generated from reading ui file 'checkoutcommitdialog.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from gitfourchette.qt import *


class Ui_CheckoutCommitDialog(object):
    def setupUi(self, CheckoutCommitDialog):
        CheckoutCommitDialog.setObjectName("CheckoutCommitDialog")
        CheckoutCommitDialog.setWindowModality(Qt.WindowModality.NonModal)
        CheckoutCommitDialog.setEnabled(True)
        CheckoutCommitDialog.resize(581, 161)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(CheckoutCommitDialog.sizePolicy().hasHeightForWidth())
        CheckoutCommitDialog.setSizePolicy(sizePolicy)
        CheckoutCommitDialog.setSizeGripEnabled(False)
        CheckoutCommitDialog.setModal(True)
        self.verticalLayout = QVBoxLayout(CheckoutCommitDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QLabel(parent=CheckoutCommitDialog)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QLayout.SizeConstraint.SetDefaultConstraint)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.switchToLocalBranchRadioButton = QRadioButton(parent=CheckoutCommitDialog)
        self.switchToLocalBranchRadioButton.setObjectName("switchToLocalBranchRadioButton")
        self.horizontalLayout.addWidget(self.switchToLocalBranchRadioButton)
        self.switchToLocalBranchComboBox = QComboBox(parent=CheckoutCommitDialog)
        self.switchToLocalBranchComboBox.setObjectName("switchToLocalBranchComboBox")
        self.horizontalLayout.addWidget(self.switchToLocalBranchComboBox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.detachedHeadRadioButton = QRadioButton(parent=CheckoutCommitDialog)
        self.detachedHeadRadioButton.setObjectName("detachedHeadRadioButton")
        self.verticalLayout.addWidget(self.detachedHeadRadioButton)
        self.createBranchRadioButton = QRadioButton(parent=CheckoutCommitDialog)
        self.createBranchRadioButton.setObjectName("createBranchRadioButton")
        self.verticalLayout.addWidget(self.createBranchRadioButton)
        self.buttonBox = QDialogButtonBox(parent=CheckoutCommitDialog)
        self.buttonBox.setOrientation(Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QDialogButtonBox.StandardButton.Cancel|QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(CheckoutCommitDialog)
        self.buttonBox.rejected.connect(CheckoutCommitDialog.reject) # type: ignore
        self.buttonBox.accepted.connect(CheckoutCommitDialog.accept) # type: ignore
        self.switchToLocalBranchRadioButton.toggled['bool'].connect(self.switchToLocalBranchComboBox.setEnabled) # type: ignore
        QMetaObject.connectSlotsByName(CheckoutCommitDialog)

    def retranslateUi(self, CheckoutCommitDialog):
        _translate = QCoreApplication.translate
        CheckoutCommitDialog.setWindowTitle(_translate("CheckoutCommitDialog", "Check out commit"))
        self.label.setText(_translate("CheckoutCommitDialog", "How do you want to check out this commit?"))
        self.switchToLocalBranchRadioButton.setText(_translate("CheckoutCommitDialog", "Switch to a &branch that points here:"))
        self.detachedHeadRadioButton.setText(_translate("CheckoutCommitDialog", "Enter &detached HEAD here"))
        self.createBranchRadioButton.setText(_translate("CheckoutCommitDialog", "Start &new branch here..."))
