# Form implementation generated from reading ui file 'commitdialog.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from gitfourchette.qt import *


class Ui_CommitDialog(object):
    def setupUi(self, CommitDialog):
        CommitDialog.setObjectName("CommitDialog")
        CommitDialog.resize(512, 208)
        CommitDialog.setModal(True)
        self.verticalLayout = QVBoxLayout(CommitDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.summaryRowLayout = QHBoxLayout()
        self.summaryRowLayout.setObjectName("summaryRowLayout")
        self.summaryEditor = QLineEdit(parent=CommitDialog)
        self.summaryEditor.setObjectName("summaryEditor")
        self.summaryRowLayout.addWidget(self.summaryEditor)
        self.counterLabel = QLabel(parent=CommitDialog)
        self.counterLabel.setEnabled(False)
        self.counterLabel.setText("000")
        self.counterLabel.setObjectName("counterLabel")
        self.summaryRowLayout.addWidget(self.counterLabel)
        self.verticalLayout.addLayout(self.summaryRowLayout)
        self.descriptionEditor = QPlainTextEdit(parent=CommitDialog)
        self.descriptionEditor.setTabChangesFocus(True)
        self.descriptionEditor.setObjectName("descriptionEditor")
        self.verticalLayout.addWidget(self.descriptionEditor)
        self.revealAuthor = QCheckBox(parent=CommitDialog)
        self.revealAuthor.setChecked(False)
        self.revealAuthor.setObjectName("revealAuthor")
        self.verticalLayout.addWidget(self.revealAuthor)
        self.authorGroupBox = QGroupBox(parent=CommitDialog)
        self.authorGroupBox.setEnabled(True)
        self.authorGroupBox.setTitle("")
        self.authorGroupBox.setFlat(False)
        self.authorGroupBox.setCheckable(False)
        self.authorGroupBox.setObjectName("authorGroupBox")
        self.verticalLayout_2 = QVBoxLayout(self.authorGroupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.authorSignature = SignatureForm(parent=self.authorGroupBox)
        self.authorSignature.setObjectName("authorSignature")
        self.verticalLayout_2.addWidget(self.authorSignature)
        self.overrideCommitterSignature = QCheckBox(parent=self.authorGroupBox)
        self.overrideCommitterSignature.setChecked(False)
        self.overrideCommitterSignature.setObjectName("overrideCommitterSignature")
        self.verticalLayout_2.addWidget(self.overrideCommitterSignature)
        self.verticalLayout.addWidget(self.authorGroupBox)
        self.detachedHeadWarning = QLabel(parent=CommitDialog)
        font = QFont()
        font.setBold(True)
        self.detachedHeadWarning.setFont(font)
        self.detachedHeadWarning.setWordWrap(True)
        self.detachedHeadWarning.setObjectName("detachedHeadWarning")
        self.verticalLayout.addWidget(self.detachedHeadWarning)
        self.buttonBox = QDialogButtonBox(parent=CommitDialog)
        self.buttonBox.setOrientation(Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QDialogButtonBox.StandardButton.Cancel|QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(CommitDialog)
        self.buttonBox.accepted.connect(CommitDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(CommitDialog.reject) # type: ignore
        self.revealAuthor.toggled['bool'].connect(self.authorGroupBox.setVisible) # type: ignore
        self.revealAuthor.toggled['bool'].connect(self.authorGroupBox.setEnabled) # type: ignore
        QMetaObject.connectSlotsByName(CommitDialog)
        CommitDialog.setTabOrder(self.summaryEditor, self.descriptionEditor)

    def retranslateUi(self, CommitDialog):
        _translate = QCoreApplication.translate
        CommitDialog.setWindowTitle(_translate("CommitDialog", "Commit"))
        self.summaryEditor.setPlaceholderText(_translate("CommitDialog", "Enter commit summary"))
        self.descriptionEditor.setPlaceholderText(_translate("CommitDialog", "Long-form description (optional)"))
        self.revealAuthor.setText(_translate("CommitDialog", "&Edit author"))
        self.overrideCommitterSignature.setToolTip(_translate("CommitDialog", "<p>Check this to use the same custom signature for the author and committer.</p>\n"
"<p>If you uncheck this, only the author will be overridden, and the committer will be set to: {0}.</p>"))
        self.overrideCommitterSignature.setText(_translate("CommitDialog", "Also override committer signature"))
        self.detachedHeadWarning.setText(_translate("CommitDialog", "Warning: You are not in any branch (detached HEAD). You should create a branch to ensure your commit won’t be lost inadvertently."))
from gitfourchette.forms.signatureform import SignatureForm
