# Form implementation generated from reading ui file 'identitydialog1.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from gitfourchette.qt import *


class Ui_IdentityDialog1(object):
    def setupUi(self, IdentityDialog1):
        IdentityDialog1.setObjectName("IdentityDialog1")
        IdentityDialog1.resize(488, 439)
        self.gridLayout = QGridLayout(IdentityDialog1)
        self.gridLayout.setObjectName("gridLayout")
        self.setGlobalIdentity = QRadioButton(parent=IdentityDialog1)
        self.setGlobalIdentity.setChecked(True)
        self.setGlobalIdentity.setObjectName("setGlobalIdentity")
        self.gridLayout.addWidget(self.setGlobalIdentity, 5, 0, 1, 3)
        spacerItem = QSpacerItem(20, 40, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem, 9, 0, 1, 1)
        self.setLocalIdentity = QRadioButton(parent=IdentityDialog1)
        self.setLocalIdentity.setObjectName("setLocalIdentity")
        self.gridLayout.addWidget(self.setLocalIdentity, 7, 0, 1, 3)
        self.label_3 = QLabel(parent=IdentityDialog1)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 2)
        self.emailEdit = QLineEdit(parent=IdentityDialog1)
        self.emailEdit.setObjectName("emailEdit")
        self.gridLayout.addWidget(self.emailEdit, 2, 2, 1, 1)
        spacerItem1 = QSpacerItem(13, 13, QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem1, 8, 0, 1, 1)
        self.help1 = QLabel(parent=IdentityDialog1)
        self.help1.setEnabled(False)
        self.help1.setWordWrap(True)
        self.help1.setObjectName("help1")
        self.gridLayout.addWidget(self.help1, 6, 1, 1, 2)
        spacerItem2 = QSpacerItem(20, 40, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Preferred)
        self.gridLayout.addItem(spacerItem2, 4, 0, 1, 1)
        spacerItem3 = QSpacerItem(20, 62, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem3, 0, 0, 1, 1)
        spacerItem4 = QSpacerItem(13, 13, QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem4, 6, 0, 1, 1)
        self.help2 = QLabel(parent=IdentityDialog1)
        self.help2.setEnabled(False)
        self.help2.setWordWrap(True)
        self.help2.setObjectName("help2")
        self.gridLayout.addWidget(self.help2, 8, 1, 1, 2)
        self.nameEdit = QLineEdit(parent=IdentityDialog1)
        self.nameEdit.setObjectName("nameEdit")
        self.gridLayout.addWidget(self.nameEdit, 1, 2, 1, 1)
        self.buttonBox = QDialogButtonBox(parent=IdentityDialog1)
        self.buttonBox.setOrientation(Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QDialogButtonBox.StandardButton.Cancel|QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 10, 0, 1, 3)
        self.label_2 = QLabel(parent=IdentityDialog1)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 2)
        self.label_3.setBuddy(self.emailEdit)
        self.label_2.setBuddy(self.nameEdit)

        self.retranslateUi(IdentityDialog1)
        self.buttonBox.accepted.connect(IdentityDialog1.accept) # type: ignore
        self.buttonBox.rejected.connect(IdentityDialog1.reject) # type: ignore
        QMetaObject.connectSlotsByName(IdentityDialog1)
        IdentityDialog1.setTabOrder(self.nameEdit, self.emailEdit)
        IdentityDialog1.setTabOrder(self.emailEdit, self.setGlobalIdentity)
        IdentityDialog1.setTabOrder(self.setGlobalIdentity, self.setLocalIdentity)

    def retranslateUi(self, IdentityDialog1):
        _translate = QCoreApplication.translate
        IdentityDialog1.setWindowTitle(_translate("IdentityDialog1", "Set up your Git identity"))
        self.setGlobalIdentity.setText(_translate("IdentityDialog1", "Set &global identity"))
        self.setLocalIdentity.setText(_translate("IdentityDialog1", "Set identity for this &repository only"))
        self.label_3.setText(_translate("IdentityDialog1", "&Email:"))
        self.help1.setText(_translate("IdentityDialog1", "Will apply to all repositories on this computer."))
        self.help2.setText(_translate("IdentityDialog1", "You will be prompted to set up an identity for other repositories."))
        self.label_2.setText(_translate("IdentityDialog1", "&Name:"))
