# Form implementation generated from reading ui file 'identitydialog2.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from gitfourchette.qt import *


class Ui_IdentityDialog2(object):
    def setupUi(self, IdentityDialog2):
        IdentityDialog2.setObjectName("IdentityDialog2")
        IdentityDialog2.resize(526, 410)
        self.gridLayout = QGridLayout(IdentityDialog2)
        self.gridLayout.setObjectName("gridLayout")
        self.identityGroupBox = QGroupBox(parent=IdentityDialog2)
        self.identityGroupBox.setObjectName("identityGroupBox")
        self.formLayout = QFormLayout(self.identityGroupBox)
        self.formLayout.setFieldGrowthPolicy(QFormLayout.FieldGrowthPolicy.ExpandingFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.label = QLabel(parent=self.identityGroupBox)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QFormLayout.ItemRole.LabelRole, self.label)
        self.nameEdit = QLineEdit(parent=self.identityGroupBox)
        self.nameEdit.setObjectName("nameEdit")
        self.formLayout.setWidget(0, QFormLayout.ItemRole.FieldRole, self.nameEdit)
        self.label_2 = QLabel(parent=self.identityGroupBox)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QFormLayout.ItemRole.LabelRole, self.label_2)
        self.emailEdit = QLineEdit(parent=self.identityGroupBox)
        self.emailEdit.setObjectName("emailEdit")
        self.formLayout.setWidget(1, QFormLayout.ItemRole.FieldRole, self.emailEdit)
        self.gridLayout.addWidget(self.identityGroupBox, 3, 0, 1, 1)
        spacerItem = QSpacerItem(20, 40, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Preferred)
        self.gridLayout.addItem(spacerItem, 2, 0, 1, 1)
        self.localIdentityCheckBox = QCheckBox(parent=IdentityDialog2)
        self.localIdentityCheckBox.setObjectName("localIdentityCheckBox")
        self.gridLayout.addWidget(self.localIdentityCheckBox, 1, 0, 1, 1)
        spacerItem1 = QSpacerItem(20, 60, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem1, 4, 0, 1, 1)
        spacerItem2 = QSpacerItem(20, 61, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem2, 0, 0, 1, 1)
        self.buttonBox = QDialogButtonBox(parent=IdentityDialog2)
        self.buttonBox.setOrientation(Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QDialogButtonBox.StandardButton.Cancel|QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 5, 0, 1, 1)
        self.label.setBuddy(self.nameEdit)
        self.label_2.setBuddy(self.emailEdit)

        self.retranslateUi(IdentityDialog2)
        self.buttonBox.accepted.connect(IdentityDialog2.accept) # type: ignore
        self.buttonBox.rejected.connect(IdentityDialog2.reject) # type: ignore
        QMetaObject.connectSlotsByName(IdentityDialog2)

    def retranslateUi(self, IdentityDialog2):
        _translate = QCoreApplication.translate
        IdentityDialog2.setWindowTitle(_translate("IdentityDialog2", "Set up your Git identity"))
        self.identityGroupBox.setTitle(_translate("IdentityDialog2", "Custom identity for “{0}”"))
        self.label.setText(_translate("IdentityDialog2", "&Name:"))
        self.label_2.setText(_translate("IdentityDialog2", "&Email:"))
        self.localIdentityCheckBox.setText(_translate("IdentityDialog2", "&Use a custom identity in repository “{0}”"))
