# Form implementation generated from reading ui file 'openrepoprogress.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from gitfourchette.localization import *
from gitfourchette.qt import *


class Ui_OpenRepoProgress(object):
    def setupUi(self, OpenRepoProgress):
        OpenRepoProgress.setObjectName("OpenRepoProgress")
        OpenRepoProgress.resize(624, 315)
        self.gridLayout = QGridLayout(OpenRepoProgress)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QSpacerItem(20, 40, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem, 0, 1, 1, 1)
        spacerItem1 = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem1, 2, 3, 1, 1)
        spacerItem2 = QSpacerItem(20, 40, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem2, 3, 1, 1, 1)
        self.label = QLabel(parent=OpenRepoProgress)
        self.label.setMinimumSize(QSize(300, 0))
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 1, 1, 2)
        self.abortButton = QPushButton(parent=OpenRepoProgress)
        self.abortButton.setFocusPolicy(Qt.FocusPolicy.NoFocus)
        self.abortButton.setText("")
        self.abortButton.setObjectName("abortButton")
        self.gridLayout.addWidget(self.abortButton, 2, 2, 1, 1)
        spacerItem3 = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem3, 2, 0, 1, 1)
        self.progressBar = QProgressBar(parent=OpenRepoProgress)
        self.progressBar.setTextVisible(False)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 2, 1, 1, 1)

        self.retranslateUi(OpenRepoProgress)
        QMetaObject.connectSlotsByName(OpenRepoProgress)

    def retranslateUi(self, OpenRepoProgress):
        OpenRepoProgress.setWindowTitle(_p("OpenRepoProgress", "Opening repository…"))
        self.label.setText(_p("OpenRepoProgress", "Opening repository…"))
        self.abortButton.setToolTip(_p("OpenRepoProgress", "Abort"))
