# Form implementation generated from reading ui file 'registersubmoduledialog.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from gitfourchette.qt import *


class Ui_RegisterSubmoduleDialog(object):
    def setupUi(self, RegisterSubmoduleDialog):
        RegisterSubmoduleDialog.setObjectName("RegisterSubmoduleDialog")
        RegisterSubmoduleDialog.resize(444, 221)
        self.formLayout = QFormLayout(RegisterSubmoduleDialog)
        self.formLayout.setObjectName("formLayout")
        self.registerExplainer = QLabel(parent=RegisterSubmoduleDialog)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.registerExplainer.sizePolicy().hasHeightForWidth())
        self.registerExplainer.setSizePolicy(sizePolicy)
        self.registerExplainer.setWordWrap(True)
        self.registerExplainer.setObjectName("registerExplainer")
        self.formLayout.setWidget(0, QFormLayout.ItemRole.SpanningRole, self.registerExplainer)
        self.remoteLabel = QLabel(parent=RegisterSubmoduleDialog)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.remoteLabel.sizePolicy().hasHeightForWidth())
        self.remoteLabel.setSizePolicy(sizePolicy)
        self.remoteLabel.setObjectName("remoteLabel")
        self.formLayout.setWidget(1, QFormLayout.ItemRole.LabelRole, self.remoteLabel)
        self.remoteComboBox = QComboBoxWithPreview(parent=RegisterSubmoduleDialog)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.MinimumExpanding, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.remoteComboBox.sizePolicy().hasHeightForWidth())
        self.remoteComboBox.setSizePolicy(sizePolicy)
        self.remoteComboBox.setObjectName("remoteComboBox")
        self.formLayout.setWidget(1, QFormLayout.ItemRole.FieldRole, self.remoteComboBox)
        self.nameLabel = QLabel(parent=RegisterSubmoduleDialog)
        self.nameLabel.setObjectName("nameLabel")
        self.formLayout.setWidget(2, QFormLayout.ItemRole.LabelRole, self.nameLabel)
        self.nameEdit = QLineEdit(parent=RegisterSubmoduleDialog)
        self.nameEdit.setClearButtonEnabled(True)
        self.nameEdit.setObjectName("nameEdit")
        self.formLayout.setWidget(2, QFormLayout.ItemRole.FieldRole, self.nameEdit)
        self.absorbExplainer = QLabel(parent=RegisterSubmoduleDialog)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.absorbExplainer.sizePolicy().hasHeightForWidth())
        self.absorbExplainer.setSizePolicy(sizePolicy)
        self.absorbExplainer.setWordWrap(True)
        self.absorbExplainer.setObjectName("absorbExplainer")
        self.formLayout.setWidget(4, QFormLayout.ItemRole.SpanningRole, self.absorbExplainer)
        self.buttonBox = QDialogButtonBox(parent=RegisterSubmoduleDialog)
        self.buttonBox.setOrientation(Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QDialogButtonBox.StandardButton.Cancel|QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.formLayout.setWidget(5, QFormLayout.ItemRole.SpanningRole, self.buttonBox)
        spacerItem = QSpacerItem(20, 1, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.MinimumExpanding)
        self.formLayout.setItem(3, QFormLayout.ItemRole.LabelRole, spacerItem)
        self.remoteLabel.setBuddy(self.remoteComboBox)
        self.nameLabel.setBuddy(self.nameEdit)

        self.retranslateUi(RegisterSubmoduleDialog)
        self.buttonBox.accepted.connect(RegisterSubmoduleDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(RegisterSubmoduleDialog.reject) # type: ignore
        QMetaObject.connectSlotsByName(RegisterSubmoduleDialog)

    def retranslateUi(self, RegisterSubmoduleDialog):
        _translate = QCoreApplication.translate
        RegisterSubmoduleDialog.setWindowTitle(_translate("RegisterSubmoduleDialog", "Register submodule"))
        self.registerExplainer.setText(_translate("RegisterSubmoduleDialog", "Submodule settings:"))
        self.remoteLabel.setText(_translate("RegisterSubmoduleDialog", "Default remote:"))
        self.nameLabel.setText(_translate("RegisterSubmoduleDialog", "Custom name:"))
        self.nameEdit.setPlaceholderText(_translate("RegisterSubmoduleDialog", "Leave blank to use the default name."))
        self.absorbExplainer.setText(_translate("RegisterSubmoduleDialog", "Once absorbed as a submodule, this copy of {sub} cannot be used independently from its superproject, {super}. This cannot be undone!"))
from gitfourchette.toolbox.qcomboboxwithpreview import QComboBoxWithPreview
