# Form implementation generated from reading ui file 'remotelinkdialog.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from gitfourchette.qt import *


class Ui_RemoteLinkDialog(object):
    def setupUi(self, RemoteLinkDialog):
        RemoteLinkDialog.setObjectName("RemoteLinkDialog")
        RemoteLinkDialog.resize(400, 300)
        self.verticalLayout = QVBoxLayout(RemoteLinkDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.statusLabel = QLabel(parent=RemoteLinkDialog)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Ignored, QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statusLabel.sizePolicy().hasHeightForWidth())
        self.statusLabel.setSizePolicy(sizePolicy)
        self.statusLabel.setText("STATUS1\n"
"STATUS2")
        self.statusLabel.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignTop)
        self.statusLabel.setObjectName("statusLabel")
        self.verticalLayout.addWidget(self.statusLabel)
        self.remoteLabel = QLabel(parent=RemoteLinkDialog)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Ignored, QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.remoteLabel.sizePolicy().hasHeightForWidth())
        self.remoteLabel.setSizePolicy(sizePolicy)
        self.remoteLabel.setText("REMOTE")
        self.remoteLabel.setObjectName("remoteLabel")
        self.verticalLayout.addWidget(self.remoteLabel)
        self.progressBar = QProgressBar(parent=RemoteLinkDialog)
        self.progressBar.setMaximum(0)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        spacerItem = QSpacerItem(20, 40, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.buttonBox = QDialogButtonBox(parent=RemoteLinkDialog)
        self.buttonBox.setOrientation(Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QDialogButtonBox.StandardButton.Abort)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(RemoteLinkDialog)
        self.buttonBox.accepted.connect(RemoteLinkDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(RemoteLinkDialog.reject) # type: ignore
        QMetaObject.connectSlotsByName(RemoteLinkDialog)

    def retranslateUi(self, RemoteLinkDialog):
        _translate = QCoreApplication.translate
        RemoteLinkDialog.setWindowTitle(_translate("RemoteLinkDialog", "Remote operation"))
