# Form implementation generated from reading ui file 'remotedialog.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from gitfourchette.qt import *


class Ui_RemoteDialog(object):
    def setupUi(self, RemoteDialog):
        RemoteDialog.setObjectName("RemoteDialog")
        RemoteDialog.setEnabled(True)
        RemoteDialog.resize(500, 296)
        RemoteDialog.setModal(True)
        self.formLayout = QFormLayout(RemoteDialog)
        self.formLayout.setFieldGrowthPolicy(QFormLayout.FieldGrowthPolicy.ExpandingFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.nameLabel = QLabel(parent=RemoteDialog)
        self.nameLabel.setObjectName("nameLabel")
        self.formLayout.setWidget(0, QFormLayout.ItemRole.LabelRole, self.nameLabel)
        self.nameEdit = QLineEdit(parent=RemoteDialog)
        self.nameEdit.setObjectName("nameEdit")
        self.formLayout.setWidget(0, QFormLayout.ItemRole.FieldRole, self.nameEdit)
        self.urlLabel = QLabel(parent=RemoteDialog)
        self.urlLabel.setObjectName("urlLabel")
        self.formLayout.setWidget(1, QFormLayout.ItemRole.LabelRole, self.urlLabel)
        self.urlEdit = QLineEdit(parent=RemoteDialog)
        self.urlEdit.setObjectName("urlEdit")
        self.formLayout.setWidget(1, QFormLayout.ItemRole.FieldRole, self.urlEdit)
        spacerItem = QSpacerItem(20, 8, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.MinimumExpanding)
        self.formLayout.setItem(2, QFormLayout.ItemRole.LabelRole, spacerItem)
        self.keyFilePicker = KeyFilePickerCheckBox(parent=RemoteDialog)
        self.keyFilePicker.setObjectName("keyFilePicker")
        self.formLayout.setWidget(3, QFormLayout.ItemRole.SpanningRole, self.keyFilePicker)
        spacerItem1 = QSpacerItem(20, 8, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.MinimumExpanding)
        self.formLayout.setItem(4, QFormLayout.ItemRole.LabelRole, spacerItem1)
        self.fetchAfterAddCheckBox = QCheckBox(parent=RemoteDialog)
        self.fetchAfterAddCheckBox.setChecked(True)
        self.fetchAfterAddCheckBox.setObjectName("fetchAfterAddCheckBox")
        self.formLayout.setWidget(5, QFormLayout.ItemRole.SpanningRole, self.fetchAfterAddCheckBox)
        self.buttonBox = QDialogButtonBox(parent=RemoteDialog)
        self.buttonBox.setOrientation(Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QDialogButtonBox.StandardButton.Cancel|QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.formLayout.setWidget(6, QFormLayout.ItemRole.SpanningRole, self.buttonBox)
        self.nameLabel.setBuddy(self.urlEdit)
        self.urlLabel.setBuddy(self.nameEdit)

        self.retranslateUi(RemoteDialog)
        self.buttonBox.accepted.connect(RemoteDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(RemoteDialog.reject) # type: ignore
        QMetaObject.connectSlotsByName(RemoteDialog)
        RemoteDialog.setTabOrder(self.nameEdit, self.urlEdit)

    def retranslateUi(self, RemoteDialog):
        _translate = QCoreApplication.translate
        RemoteDialog.setWindowTitle(_translate("RemoteDialog", "Edit remote"))
        self.nameLabel.setText(_translate("RemoteDialog", "&Name:"))
        self.urlLabel.setText(_translate("RemoteDialog", "&URL:"))
        self.keyFilePicker.setText(_translate("RemoteDialog", "Log in with custom &key file"))
        self.fetchAfterAddCheckBox.setText(_translate("RemoteDialog", "Fetch remote branches after adding"))
from gitfourchette.forms.keyfilepickercheckbox import KeyFilePickerCheckBox
