# Form implementation generated from reading ui file 'remotedialog.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from gitfourchette.qt import *


class Ui_RemoteDialog(object):
    def setupUi(self, RemoteDialog):
        RemoteDialog.setObjectName("RemoteDialog")
        RemoteDialog.setEnabled(True)
        RemoteDialog.resize(500, 296)
        RemoteDialog.setModal(True)
        self.formLayout = QFormLayout(RemoteDialog)
        self.formLayout.setFieldGrowthPolicy(QFormLayout.FieldGrowthPolicy.ExpandingFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.nameLabel = QLabel(parent=RemoteDialog)
        self.nameLabel.setObjectName("nameLabel")
        self.formLayout.setWidget(0, QFormLayout.ItemRole.LabelRole, self.nameLabel)
        self.nameEdit = QLineEdit(parent=RemoteDialog)
        self.nameEdit.setObjectName("nameEdit")
        self.formLayout.setWidget(0, QFormLayout.ItemRole.FieldRole, self.nameEdit)
        self.urlLabel = QLabel(parent=RemoteDialog)
        self.urlLabel.setObjectName("urlLabel")
        self.formLayout.setWidget(1, QFormLayout.ItemRole.LabelRole, self.urlLabel)
        self.urlEdit = QLineEdit(parent=RemoteDialog)
        self.urlEdit.setObjectName("urlEdit")
        self.formLayout.setWidget(1, QFormLayout.ItemRole.FieldRole, self.urlEdit)
        self.keyFileGroupBox = QGroupBox(parent=RemoteDialog)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.keyFileGroupBox.sizePolicy().hasHeightForWidth())
        self.keyFileGroupBox.setSizePolicy(sizePolicy)
        self.keyFileGroupBox.setCheckable(True)
        self.keyFileGroupBox.setObjectName("keyFileGroupBox")
        self.gridLayout = QGridLayout(self.keyFileGroupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.keyFileBrowseButton = QPushButton(parent=self.keyFileGroupBox)
        self.keyFileBrowseButton.setObjectName("keyFileBrowseButton")
        self.gridLayout.addWidget(self.keyFileBrowseButton, 0, 1, 1, 1)
        self.keyFilePathEdit = QLineEdit(parent=self.keyFileGroupBox)
        self.keyFilePathEdit.setObjectName("keyFilePathEdit")
        self.gridLayout.addWidget(self.keyFilePathEdit, 0, 0, 1, 1)
        self.formLayout.setWidget(3, QFormLayout.ItemRole.SpanningRole, self.keyFileGroupBox)
        self.buttonBox = QDialogButtonBox(parent=RemoteDialog)
        self.buttonBox.setOrientation(Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QDialogButtonBox.StandardButton.Cancel|QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.formLayout.setWidget(6, QFormLayout.ItemRole.SpanningRole, self.buttonBox)
        spacerItem = QSpacerItem(20, 8, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.MinimumExpanding)
        self.formLayout.setItem(2, QFormLayout.ItemRole.LabelRole, spacerItem)
        spacerItem1 = QSpacerItem(20, 8, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.MinimumExpanding)
        self.formLayout.setItem(4, QFormLayout.ItemRole.LabelRole, spacerItem1)
        self.fetchAfterAddCheckBox = QCheckBox(parent=RemoteDialog)
        self.fetchAfterAddCheckBox.setChecked(True)
        self.fetchAfterAddCheckBox.setObjectName("fetchAfterAddCheckBox")
        self.formLayout.setWidget(5, QFormLayout.ItemRole.SpanningRole, self.fetchAfterAddCheckBox)
        self.nameLabel.setBuddy(self.urlEdit)
        self.urlLabel.setBuddy(self.nameEdit)

        self.retranslateUi(RemoteDialog)
        self.buttonBox.accepted.connect(RemoteDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(RemoteDialog.reject) # type: ignore
        QMetaObject.connectSlotsByName(RemoteDialog)
        RemoteDialog.setTabOrder(self.nameEdit, self.urlEdit)
        RemoteDialog.setTabOrder(self.urlEdit, self.keyFileGroupBox)
        RemoteDialog.setTabOrder(self.keyFileGroupBox, self.keyFilePathEdit)
        RemoteDialog.setTabOrder(self.keyFilePathEdit, self.keyFileBrowseButton)

    def retranslateUi(self, RemoteDialog):
        _translate = QCoreApplication.translate
        RemoteDialog.setWindowTitle(_translate("RemoteDialog", "Edit remote"))
        self.nameLabel.setText(_translate("RemoteDialog", "&Name:"))
        self.urlLabel.setText(_translate("RemoteDialog", "&URL:"))
        self.keyFileGroupBox.setTitle(_translate("RemoteDialog", "Use a custom &key file to access this remote"))
        self.keyFileBrowseButton.setText(_translate("RemoteDialog", "&Browse..."))
        self.keyFilePathEdit.setPlaceholderText(_translate("RemoteDialog", "Path to public or private key"))
        self.fetchAfterAddCheckBox.setText(_translate("RemoteDialog", "Fetch remote branches after adding"))
