# Form implementation generated from reading ui file 'statusform.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from gitfourchette.qt import *


class Ui_StatusForm(object):
    def setupUi(self, StatusForm):
        StatusForm.setObjectName("StatusForm")
        StatusForm.resize(455, 125)
        StatusForm.setWindowTitle("Form")
        self.verticalLayout = QVBoxLayout(StatusForm)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.stackedWidget = QStackedWidget(parent=StatusForm)
        self.stackedWidget.setObjectName("stackedWidget")
        self.progressPage = QWidget()
        self.progressPage.setObjectName("progressPage")
        self.verticalLayout_2 = QVBoxLayout(self.progressPage)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.linkMessage = QLabel(parent=self.progressPage)
        self.linkMessage.setText("blah\n"
"blah")
        self.linkMessage.setWordWrap(True)
        self.linkMessage.setObjectName("linkMessage")
        self.verticalLayout_2.addWidget(self.linkMessage)
        self.progressBar = QProgressBar(parent=self.progressPage)
        self.progressBar.setMinimum(0)
        self.progressBar.setMaximum(0)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_2.addWidget(self.progressBar)
        self.stackedWidget.addWidget(self.progressPage)
        self.blurbPage = QWidget()
        self.blurbPage.setObjectName("blurbPage")
        self.horizontalLayout_2 = QHBoxLayout(self.blurbPage)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.blurbLabel = QLabel(parent=self.blurbPage)
        self.blurbLabel.setText("Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.")
        self.blurbLabel.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignTop)
        self.blurbLabel.setWordWrap(True)
        self.blurbLabel.setTextInteractionFlags(Qt.TextInteractionFlag.LinksAccessibleByMouse|Qt.TextInteractionFlag.TextSelectableByMouse)
        self.blurbLabel.setObjectName("blurbLabel")
        self.horizontalLayout_2.addWidget(self.blurbLabel)
        self.stackedWidget.addWidget(self.blurbPage)
        self.verticalLayout.addWidget(self.stackedWidget)

        self.retranslateUi(StatusForm)
        self.stackedWidget.setCurrentIndex(1)
        QMetaObject.connectSlotsByName(StatusForm)

    def retranslateUi(self, StatusForm):
        pass
