# Form implementation generated from reading ui file 'stashdialog.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from gitfourchette.qt import *


class Ui_StashDialog(object):
    def setupUi(self, StashDialog):
        StashDialog.setObjectName("StashDialog")
        StashDialog.setWindowModality(Qt.WindowModality.NonModal)
        StashDialog.setEnabled(True)
        StashDialog.resize(461, 432)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(StashDialog.sizePolicy().hasHeightForWidth())
        StashDialog.setSizePolicy(sizePolicy)
        StashDialog.setSizeGripEnabled(False)
        StashDialog.setModal(True)
        self.formLayout = QFormLayout(StashDialog)
        self.formLayout.setFieldGrowthPolicy(QFormLayout.FieldGrowthPolicy.ExpandingFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.messageLabel = QLabel(parent=StashDialog)
        self.messageLabel.setObjectName("messageLabel")
        self.formLayout.setWidget(0, QFormLayout.ItemRole.LabelRole, self.messageLabel)
        self.messageEdit = QLineEdit(parent=StashDialog)
        self.messageEdit.setObjectName("messageEdit")
        self.formLayout.setWidget(0, QFormLayout.ItemRole.FieldRole, self.messageEdit)
        self.optionsLabel = QLabel(parent=StashDialog)
        self.optionsLabel.setObjectName("optionsLabel")
        self.formLayout.setWidget(1, QFormLayout.ItemRole.LabelRole, self.optionsLabel)
        self.cleanupCheckBox = QCheckBox(parent=StashDialog)
        self.cleanupCheckBox.setChecked(True)
        self.cleanupCheckBox.setObjectName("cleanupCheckBox")
        self.formLayout.setWidget(1, QFormLayout.ItemRole.FieldRole, self.cleanupCheckBox)
        self.line = QFrame(parent=StashDialog)
        self.line.setFrameShape(QFrame.Shape.HLine)
        self.line.setFrameShadow(QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.formLayout.setWidget(3, QFormLayout.ItemRole.SpanningRole, self.line)
        self.willBackUpChangesLabel = QLabel(parent=StashDialog)
        self.willBackUpChangesLabel.setObjectName("willBackUpChangesLabel")
        self.formLayout.setWidget(4, QFormLayout.ItemRole.SpanningRole, self.willBackUpChangesLabel)
        self.willRemoveChangesLabel = QLabel(parent=StashDialog)
        self.willRemoveChangesLabel.setObjectName("willRemoveChangesLabel")
        self.formLayout.setWidget(5, QFormLayout.ItemRole.SpanningRole, self.willRemoveChangesLabel)
        self.willKeepChangesLabel = QLabel(parent=StashDialog)
        self.willKeepChangesLabel.setObjectName("willKeepChangesLabel")
        self.formLayout.setWidget(6, QFormLayout.ItemRole.SpanningRole, self.willKeepChangesLabel)
        self.fileList = QListWidget(parent=StashDialog)
        self.fileList.setSelectionMode(QAbstractItemView.SelectionMode.ExtendedSelection)
        self.fileList.setObjectName("fileList")
        self.formLayout.setWidget(7, QFormLayout.ItemRole.FieldRole, self.fileList)
        self.buttonBox = QDialogButtonBox(parent=StashDialog)
        self.buttonBox.setOrientation(Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QDialogButtonBox.StandardButton.Cancel|QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.formLayout.setWidget(17, QFormLayout.ItemRole.FieldRole, self.buttonBox)
        self.indexAndWtWarning = QLabel(parent=StashDialog)
        self.indexAndWtWarning.setWordWrap(True)
        self.indexAndWtWarning.setObjectName("indexAndWtWarning")
        self.formLayout.setWidget(8, QFormLayout.ItemRole.SpanningRole, self.indexAndWtWarning)
        self.messageLabel.setBuddy(self.messageEdit)

        self.retranslateUi(StashDialog)
        self.buttonBox.rejected.connect(StashDialog.reject) # type: ignore
        self.buttonBox.accepted.connect(StashDialog.accept) # type: ignore
        self.cleanupCheckBox.clicked['bool'].connect(self.willRemoveChangesLabel.setVisible) # type: ignore
        self.cleanupCheckBox.clicked['bool'].connect(self.willKeepChangesLabel.setHidden) # type: ignore
        QMetaObject.connectSlotsByName(StashDialog)

    def retranslateUi(self, StashDialog):
        _translate = QCoreApplication.translate
        StashDialog.setWindowTitle(_translate("StashDialog", "New stash"))
        self.messageLabel.setText(_translate("StashDialog", "&Description"))
        self.messageEdit.setPlaceholderText(_translate("StashDialog", "Optional stash message"))
        self.optionsLabel.setText(_translate("StashDialog", "Options"))
        self.cleanupCheckBox.setToolTip(_translate("StashDialog", "Normally, stashed changes are removed from the working directory.\n"
"Untick this to leave the stashed changes intact instead."))
        self.cleanupCheckBox.setText(_translate("StashDialog", "&Remove stashed changes after stashing"))
        self.willBackUpChangesLabel.setText(_translate("StashDialog", "The stash will back up all changes to the files ticked below."))
        self.willRemoveChangesLabel.setText(_translate("StashDialog", "These changes will then be removed from the working directory."))
        self.willKeepChangesLabel.setText(_translate("StashDialog", "These changes will remain in the working directory."))
        self.indexAndWtWarning.setText(_translate("StashDialog", "Warning: Some of the files have both staged and unstaged changes. Those changes will be combined in the stash."))
