# Form implementation generated from reading ui file 'searchbar.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from gitfourchette.localization import *
from gitfourchette.qt import *


class Ui_SearchBar(object):
    def setupUi(self, SearchBar):
        SearchBar.setObjectName("SearchBar")
        SearchBar.resize(329, 26)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(SearchBar.sizePolicy().hasHeightForWidth())
        SearchBar.setSizePolicy(sizePolicy)
        SearchBar.setAutoFillBackground(True)
        self.horizontalLayout = QHBoxLayout(SearchBar)
        self.horizontalLayout.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit = QLineEdit(parent=SearchBar)
        self.lineEdit.setClearButtonEnabled(True)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.forwardButton = QToolButton(parent=SearchBar)
        self.forwardButton.setText("↓")
        self.forwardButton.setObjectName("forwardButton")
        self.horizontalLayout.addWidget(self.forwardButton)
        self.backwardButton = QToolButton(parent=SearchBar)
        self.backwardButton.setText("↑")
        self.backwardButton.setObjectName("backwardButton")
        self.horizontalLayout.addWidget(self.backwardButton)
        self.closeButton = QToolButton(parent=SearchBar)
        self.closeButton.setObjectName("closeButton")
        self.horizontalLayout.addWidget(self.closeButton)

        self.retranslateUi(SearchBar)
        QMetaObject.connectSlotsByName(SearchBar)

    def retranslateUi(self, SearchBar):
        SearchBar.setWindowTitle(_p("SearchBar", "Search"))
        self.lineEdit.setPlaceholderText(_p("SearchBar", "Search…"))
        self.forwardButton.setToolTip(_p("SearchBar", "Next Occurrence"))
        self.backwardButton.setToolTip(_p("SearchBar", "Previous Occurrence"))
        self.closeButton.setToolTip(_p("SearchBar", "Close Search Bar"))
        self.closeButton.setText(_p("SearchBar", "Done"))
