# Form implementation generated from reading ui file 'signatureform.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from gitfourchette.qt import *


class Ui_SignatureForm(object):
    def setupUi(self, SignatureForm):
        SignatureForm.setObjectName("SignatureForm")
        SignatureForm.resize(340, 96)
        SignatureForm.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.formLayout = QFormLayout(SignatureForm)
        self.formLayout.setFieldGrowthPolicy(QFormLayout.FieldGrowthPolicy.ExpandingFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.nameLabel = QLabel(parent=SignatureForm)
        self.nameLabel.setObjectName("nameLabel")
        self.formLayout.setWidget(0, QFormLayout.ItemRole.LabelRole, self.nameLabel)
        self.nameEdit = QLineEdit(parent=SignatureForm)
        self.nameEdit.setObjectName("nameEdit")
        self.formLayout.setWidget(0, QFormLayout.ItemRole.FieldRole, self.nameEdit)
        self.emailLabel = QLabel(parent=SignatureForm)
        self.emailLabel.setObjectName("emailLabel")
        self.formLayout.setWidget(1, QFormLayout.ItemRole.LabelRole, self.emailLabel)
        self.emailEdit = QLineEdit(parent=SignatureForm)
        self.emailEdit.setObjectName("emailEdit")
        self.formLayout.setWidget(1, QFormLayout.ItemRole.FieldRole, self.emailEdit)
        self.timeLabel = QLabel(parent=SignatureForm)
        self.timeLabel.setObjectName("timeLabel")
        self.formLayout.setWidget(3, QFormLayout.ItemRole.LabelRole, self.timeLabel)
        self.horizontalLayout = QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.timeEdit = QDateTimeEdit(parent=SignatureForm)
        self.timeEdit.setCurrentSection(QDateTimeEdit.Section.YearSection)
        self.timeEdit.setDisplayFormat("yyyy-MM-dd HH:mm:ss (t)")
        self.timeEdit.setCalendarPopup(True)
        self.timeEdit.setTimeSpec(Qt.TimeSpec.LocalTime)
        self.timeEdit.setObjectName("timeEdit")
        self.horizontalLayout.addWidget(self.timeEdit)
        self.nowButton = QPushButton(parent=SignatureForm)
        self.nowButton.setObjectName("nowButton")
        self.horizontalLayout.addWidget(self.nowButton)
        self.formLayout.setLayout(3, QFormLayout.ItemRole.FieldRole, self.horizontalLayout)
        self.nameLabel.setBuddy(self.nameEdit)
        self.emailLabel.setBuddy(self.emailEdit)
        self.timeLabel.setBuddy(self.timeEdit)

        self.retranslateUi(SignatureForm)
        QMetaObject.connectSlotsByName(SignatureForm)
        SignatureForm.setTabOrder(self.nameEdit, self.emailEdit)
        SignatureForm.setTabOrder(self.emailEdit, self.timeEdit)
        SignatureForm.setTabOrder(self.timeEdit, self.nowButton)

    def retranslateUi(self, SignatureForm):
        _translate = QCoreApplication.translate
        SignatureForm.setWindowTitle(_translate("SignatureForm", "Signature"))
        self.nameLabel.setText(_translate("SignatureForm", "&Name:"))
        self.emailLabel.setText(_translate("SignatureForm", "&Email:"))
        self.timeLabel.setText(_translate("SignatureForm", "&Time:"))
        self.nowButton.setText(_translate("SignatureForm", "Now"))
