# Form implementation generated from reading ui file 'unloadedrepoplaceholder.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from gitfourchette.qt import *


class Ui_UnloadedRepoPlaceholder(object):
    def setupUi(self, UnloadedRepoPlaceholder):
        UnloadedRepoPlaceholder.setObjectName("UnloadedRepoPlaceholder")
        UnloadedRepoPlaceholder.resize(670, 327)
        self.gridLayout = QGridLayout(UnloadedRepoPlaceholder)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QSpacerItem(20, 109, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem, 5, 1, 1, 1)
        spacerItem1 = QSpacerItem(141, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem1, 4, 0, 1, 1)
        self.label = QLabel(parent=UnloadedRepoPlaceholder)
        self.label.setMinimumSize(QSize(300, 0))
        self.label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 3, 1, 1, 1)
        self.nameLabel = QLabel(parent=UnloadedRepoPlaceholder)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nameLabel.sizePolicy().hasHeightForWidth())
        self.nameLabel.setSizePolicy(sizePolicy)
        self.nameLabel.setMaximumSize(QSize(300, 16777215))
        self.nameLabel.setText("Long Long Long Long Long Long Long Long Long Long Name")
        self.nameLabel.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.nameLabel.setObjectName("nameLabel")
        self.gridLayout.addWidget(self.nameLabel, 2, 1, 1, 1)
        self.loadButton = QPushButton(parent=UnloadedRepoPlaceholder)
        self.loadButton.setObjectName("loadButton")
        self.gridLayout.addWidget(self.loadButton, 4, 1, 1, 1)
        spacerItem2 = QSpacerItem(20, 109, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem2, 0, 1, 1, 1)
        spacerItem3 = QSpacerItem(140, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem3, 4, 2, 1, 1)
        self.icon = QLabel(parent=UnloadedRepoPlaceholder)
        self.icon.setText("ICON")
        self.icon.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.icon.setObjectName("icon")
        self.gridLayout.addWidget(self.icon, 1, 1, 1, 1)

        self.retranslateUi(UnloadedRepoPlaceholder)
        QMetaObject.connectSlotsByName(UnloadedRepoPlaceholder)

    def retranslateUi(self, UnloadedRepoPlaceholder):
        _translate = QCoreApplication.translate
        UnloadedRepoPlaceholder.setWindowTitle(_translate("UnloadedRepoPlaceholder", "Form"))
        self.label.setText(_translate("UnloadedRepoPlaceholder", "This repository is ready to be loaded."))
        self.loadButton.setText(_translate("UnloadedRepoPlaceholder", "Load"))
