# Form implementation generated from reading ui file 'welcomewidget.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from gitfourchette.qt import *


class Ui_WelcomeWidget(object):
    def setupUi(self, WelcomeWidget):
        WelcomeWidget.setObjectName("WelcomeWidget")
        WelcomeWidget.resize(521, 288)
        self.gridLayout = QGridLayout(WelcomeWidget)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QSpacerItem(20, 27, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem, 0, 1, 1, 1)
        spacerItem1 = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem1, 5, 0, 1, 1)
        self.cloneRepoButton = QPushButton(parent=WelcomeWidget)
        self.cloneRepoButton.setObjectName("cloneRepoButton")
        self.gridLayout.addWidget(self.cloneRepoButton, 6, 1, 1, 1)
        self.newRepoButton = QPushButton(parent=WelcomeWidget)
        self.newRepoButton.setObjectName("newRepoButton")
        self.gridLayout.addWidget(self.newRepoButton, 4, 1, 1, 1)
        self.openRepoButton = QPushButton(parent=WelcomeWidget)
        self.openRepoButton.setObjectName("openRepoButton")
        self.gridLayout.addWidget(self.openRepoButton, 5, 1, 1, 1)
        spacerItem2 = QSpacerItem(20, 27, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem2, 3, 1, 1, 1)
        spacerItem3 = QSpacerItem(20, 27, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem3, 7, 1, 1, 1)
        spacerItem4 = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem4, 5, 2, 1, 1)
        self.welcomeLabel = QLabel(parent=WelcomeWidget)
        self.welcomeLabel.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.welcomeLabel.setObjectName("welcomeLabel")
        self.gridLayout.addWidget(self.welcomeLabel, 2, 0, 1, 3)
        self.logoLabel = QLabel(parent=WelcomeWidget)
        self.logoLabel.setText("{app}")
        self.logoLabel.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.logoLabel.setObjectName("logoLabel")
        self.gridLayout.addWidget(self.logoLabel, 1, 0, 1, 3)

        self.retranslateUi(WelcomeWidget)
        QMetaObject.connectSlotsByName(WelcomeWidget)

    def retranslateUi(self, WelcomeWidget):
        _translate = QCoreApplication.translate
        WelcomeWidget.setWindowTitle(_translate("WelcomeWidget", "Welcome"))
        self.cloneRepoButton.setText(_translate("WelcomeWidget", "Clone remote repository"))
        self.newRepoButton.setText(_translate("WelcomeWidget", "New empty repository"))
        self.openRepoButton.setText(_translate("WelcomeWidget", "Open local repository"))
        self.welcomeLabel.setText(_translate("WelcomeWidget", "Welcome to {app} {version}!"))
