name: AppImage

on: [workflow_dispatch]

env:
  PYVER: "3.12"
  QT_API: "pyqt6"

jobs:
  appimage:
    runs-on: ubuntu-20.04  # Use oldest available Ubuntu for maximum glibc compatibility
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "${{ env.PYVER }}" }
      - run: python -m pip install --upgrade pip setuptools wheel

      #########################################################################
      # TODO: REMOVE THIS once PyQt6 6.8+ installs cleanly on CI runner (December 2024)
      - run: sed -E -i 's/^pyqt6 = \["pyqt6"\]/pyqt6 = ["pyqt6<6.8"]/g' pyproject.toml
      #########################################################################

      - run: python -m pip install --upgrade -e .[$QT_API]  # install dependencies (installing GF itself isn't necessary)
      - run: python -m pip install --upgrade git+https://github.com/niess/python-appimage
      - name: Build AppImage
        run: |
          PYVER=$PYVER QT_API=$QT_API ./pkg/appimage/build-appimage.sh
          echo "ARTIFACT_NAME=$(cd build && ls GitFourchette*.AppImage)" >> $GITHUB_ENV
      - uses: actions/upload-artifact@v4
        with:
          path: build/GitFourchette*.AppImage
          name: ${{env.ARTIFACT_NAME}}
          compression-level: 0
